### ISSUE TITLE
Looks great!

### ISSUE THREAD

**Issue by fessacchiotto** [logaretm/vue-use-form#1]
Looking forward to using it and give some constructive feedback. What do you think is missing to be considered production-ready, albeit in beta form? Any backstage thought  on this library? Cheers!

**Comment by logaretm** [comment]
Thanks, not a lot is missing. So far this is the missing stuff:

- Dynamic Rules (for object format).
- Docs.
- Tests.

Well, at least the beta needs these stuff. Feel free to throw in some suggestions. Maybe even help me a bit 😄

**Comment by fessacchiotto** [comment]
Dear Abdelrahman. I’d love to help. As soon as I’ll be allowed by my work I’ll see how I could be useful (I’m just an average programmer though...). Thanks again for sharing your work!

**Comment by logaretm** [comment]
We are all average programmers 😀, looking forward to your contribution and thanks for the kind words.
